<div class="alert alert-block alert-info">

# Method 1 - List comprehension
</div>

In [9]:
inputMatrix = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
for row in inputMatrix:
    print(row)
result = [[inputMatrix[j][i] for j in range(len(inputMatrix))] for i in range(len(inputMatrix[0]))] #1 line code
print("TRANSPOSE OF THE MATRIX")
for r in result:
    print(r)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]
TRANSPOSE OF THE MATRIX
[1, 4, 7, 10]
[2, 5, 8, 11]
[3, 6, 9, 12]


<div class="alert alert-block alert-info">

# Method 2 - Using zip 
</div>

In [11]:
inputMatrix = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
for row in inputMatrix:
    print(row)
result = zip(*inputMatrix) #1 line code
print("TRANSPOSE OF THE MATRIX")
for r in result:
    print(r)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]
TRANSPOSE OF THE MATRIX
(1, 4, 7, 10)
(2, 5, 8, 11)
(3, 6, 9, 12)


<div class="alert alert-block alert-info">

# Method 3 - Using numpy
</div>

In [12]:
import numpy as np
inputMatrix = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
for row in inputMatrix:
    print(row)
result = np.transpose(inputMatrix)
for r in result:
    print(r)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]
[ 1  4  7 10]
[ 2  5  8 11]
[ 3  6  9 12]


In [19]:
from itertools import chain
L = chain(*inputMatrix)
n = len(inputMatrix[0])

In [21]:
result = [L[i::n] for i in range(n)]

TypeError: 'itertools.chain' object is not subscriptable